Updates formatting.

diff --git a/bin/mp4merge b/bin/mp4merge
--- a/bin/mp4merge
+++ b/bin/mp4merge
@@ -5,7 +5,7 @@ output_arg=${!#}
 
 main() {
   check_ffmpeg
-  check_input_args $input_args 
+  check_input_args $input_args
   check_output_arg $output_arg
   merge
 }
@@ -24,14 +24,14 @@ print_usage_and_exit() {
 check_ffmpeg() {
   if [ ! which ffmpeg > /dev/null 2>&1 ] ; then
     >&2 echo "please install ffmpeg for this script to work"
-    exit 1 
+    exit 1
   fi
 }
 
 check_input_args() {
-  if [ "$#" -lt 2 ]; then
-      >&2 echo "need at least 2 file operands"
-      print_usage_and_exit
+  if [ "$#" -lt 2 ] ; then
+    >&2 echo "need at least 2 file operands"
+    print_usage_and_exit
   fi
   for f in $@; do
     if [ ! -f $f ] ; then
@@ -42,9 +42,9 @@ check_input_args() {
 }
 
 check_output_arg() {
-  if [ "$#" -eq 0 ]; then
-      >&2 echo "missing destinaion operand"
-      print_usage_and_exit
+  if [ "$#" -eq 0 ] ; then
+    >&2 echo "missing destinaion operand"
+    print_usage_and_exit
   fi
   if [ -f $1 ] ; then
     >&2 echo "output file $1 already exists"
